from rdflib.namespace import DefinedNamespace, Namespace
from rdflib.term import URIRef
from rdflib import URIRef, Literal

class ACTOLite(DefinedNamespace):
    _NS = Namespace("http://purl.org/lmjxt/actolite#")
    op_CDay : URIRef
    op_CMonth : URIRef
    op_CTime : URIRef
    op_CYear : URIRef
    op_DiWang : URIRef
    op_NianHao : URIRef
    op_TimeTypeByCertainty : URIRef
    op_toGCalendar : URIRef
    dp_CDay_Text : URIRef
    dp_CMonth_Text : URIRef
    dp_CTime_Text : URIRef
    dp_CYear_Text : URIRef
    dp_EE_Label : URIRef
    dp_EE_Value : URIRef
    c_ACTOEntity : URIRef
    c_AfterTime : URIRef
    c_AroundTime : URIRef
    c_BeforeTime : URIRef
    c_CDay : URIRef
    c_CDay_GanZhi : URIRef
    c_CDay_ShuXu : URIRef
    c_CDay_YueXiang : URIRef
    c_CMonth : URIRef
    c_CMonth_GanZhi : URIRef
    c_CMonth_ShuXu : URIRef
    c_CTime : URIRef
    c_CTime_ChenKe : URIRef
    c_CTime_GengDian : URIRef
    c_CTime_LouKe : URIRef
    c_CTime_ShiChen : URIRef
    c_CTime_ShiDuan : URIRef
    c_CYear : URIRef
    c_CYear_DiWang : URIRef
    c_CYear_GanZhi : URIRef
    c_CYear_NianHao : URIRef
    c_CertainlyTime : URIRef
    c_ExpressElement : URIRef
    c_TimeByCertainty : URIRef
    c_UncertainlyTime : URIRef
    i_AfterTime : URIRef
    i_AroundTime : URIRef
    i_BeforeTime : URIRef
    i_CertainlyTime : URIRef
    i_ee_10Yue : URIRef
    i_ee_11Yue : URIRef
    i_ee_12Yue : URIRef
    i_ee_1Yue : URIRef
    i_ee_2Yue : URIRef
    i_ee_3Yue : URIRef
    i_ee_4Yue : URIRef
    i_ee_5Yue : URIRef
    i_ee_6Yue : URIRef
    i_ee_7Yue : URIRef
    i_ee_8Yue : URIRef
    i_ee_9Yue : URIRef
    i_ee_Bing : URIRef
    i_ee_BingChen : URIRef
    i_ee_BingShen : URIRef
    i_ee_BingWu : URIRef
    i_ee_BingXu : URIRef
    i_ee_BingYin : URIRef
    i_ee_BingZi : URIRef
    i_ee_Chen : URIRef
    i_ee_ChiFenRuo : URIRef
    i_ee_Chou : URIRef
    i_ee_ChunHuo : URIRef
    i_ee_ChunShou : URIRef
    i_ee_ChunWei : URIRef
    i_ee_DaHuangLuo : URIRef
    i_ee_DaHuo : URIRef
    i_ee_DaLiang : URIRef
    i_ee_DaYuanXian : URIRef
    i_ee_DanE : URIRef
    i_ee_Ding : URIRef
    i_ee_DingChou : URIRef
    i_ee_DingHai : URIRef
    i_ee_DingMao : URIRef
    i_ee_DingSi : URIRef
    i_ee_DingWei : URIRef
    i_ee_DingYou : URIRef
    i_ee_DunZang : URIRef
    i_ee_Geng : URIRef
    i_ee_GengChen : URIRef
    i_ee_GengShen : URIRef
    i_ee_GengWu : URIRef
    i_ee_GengXu : URIRef
    i_ee_GengYin : URIRef
    i_ee_GengZi : URIRef
    i_ee_Gou : URIRef
    i_ee_Gui : URIRef
    i_ee_GuiChou : URIRef
    i_ee_GuiHai : URIRef
    i_ee_GuiMao : URIRef
    i_ee_GuiSi : URIRef
    i_ee_GuiWei : URIRef
    i_ee_GuiYou : URIRef
    i_ee_Hai : URIRef
    i_ee_Hou : URIRef
    i_ee_Hu : URIRef
    i_ee_HuiRi : URIRef
    i_ee_Ji : URIRef
    i_ee_Ji2 : URIRef
    i_ee_JiChou : URIRef
    i_ee_JiHai : URIRef
    i_ee_JiMao : URIRef
    i_ee_JiSi : URIRef
    i_ee_JiWang : URIRef
    i_ee_JiWei : URIRef
    i_ee_JiYou : URIRef
    i_ee_Jia : URIRef
    i_ee_JiaChen : URIRef
    i_ee_JiaShen : URIRef
    i_ee_JiaWu : URIRef
    i_ee_JiaXu : URIRef
    i_ee_JiaYin : URIRef
    i_ee_JiaZi : URIRef
    i_ee_JiangLou : URIRef
    i_ee_JuZi : URIRef
    i_ee_KunDun : URIRef
    i_ee_Long : URIRef
    i_ee_Ma : URIRef
    i_ee_Mao : URIRef
    i_ee_Niu : URIRef
    i_ee_Ren : URIRef
    i_ee_RenChen : URIRef
    i_ee_RenShen : URIRef
    i_ee_RenWu : URIRef
    i_ee_RenXu : URIRef
    i_ee_RenYin : URIRef
    i_ee_RenZi : URIRef
    i_ee_RunYue : URIRef
    i_ee_She : URIRef
    i_ee_SheTiGe : URIRef
    i_ee_Shen : URIRef
    i_ee_ShiShen : URIRef
    i_ee_ShouXing : URIRef
    i_ee_Shu : URIRef
    i_ee_ShuoRi : URIRef
    i_ee_Si : URIRef
    i_ee_Tu : URIRef
    i_ee_TunTan : URIRef
    i_ee_WangRi : URIRef
    i_ee_Wei : URIRef
    i_ee_Wu : URIRef
    i_ee_Wu2 : URIRef
    i_ee_WuChen : URIRef
    i_ee_WuShen : URIRef
    i_ee_WuWu : URIRef
    i_ee_WuXu : URIRef
    i_ee_WuYin : URIRef
    i_ee_WuZi : URIRef
    i_ee_XiMu : URIRef
    i_ee_XieQia : URIRef
    i_ee_Xin : URIRef
    i_ee_XinChou : URIRef
    i_ee_XinHai : URIRef
    i_ee_XinMao : URIRef
    i_ee_XinSi : URIRef
    i_ee_XinWei : URIRef
    i_ee_XinYou : URIRef
    i_ee_XingJi : URIRef
    i_ee_Xu : URIRef
    i_ee_XuanXiao : URIRef
    i_ee_YanMao : URIRef
    i_ee_Yang : URIRef
    i_ee_Yi : URIRef
    i_ee_YiChou : URIRef
    i_ee_YiHai : URIRef
    i_ee_YiMao : URIRef
    i_ee_YiSi : URIRef
    i_ee_YiWei : URIRef
    i_ee_YiYou : URIRef
    i_ee_Yin : URIRef
    i_ee_You : URIRef
    i_ee_ZhiXu : URIRef
    i_ee_Zhu : URIRef
    i_ee_Zi : URIRef
    i_ee_ZuoE : URIRef

    def getURIByEELabel(g,label):
        return g.value(predicate=ACTOLite.dp_EE_Label, object= Literal(label,lang="zh"))
    def getEEValueByEELabel(g,label):
        s=g.value(predicate=ACTOLite.dp_EE_Label, object= Literal(label,lang="zh"))
        return g.value(subject=s,predicate=ACTOLite.dp_EE_Value)