from rdflib.namespace import DefinedNamespace, Namespace
from rdflib.term import URIRef

class JKO(DefinedNamespace):
    """
    JKO(Jiao Kan Ontology)校勘本体。
    """

    _NS = Namespace("http://purl.org/lmjxt/jiaokanontology#")
    op_CuoWuLeiXing : URIRef
    """ 错误类型 """
    op_CuoWuYuanYin : URIRef
    """ 错误原因 """
    op_JiaoKanFangFa : URIRef
    """ 校勘方法 """
    op_JiaoKanJi : URIRef
    """ 校勘记 """
    op_JiaoKanJiLaiYuan : URIRef
    """ 校勘记来源 """
    op_JiaoKanJiLeiXing : URIRef
    """ 校勘记类型 """
    op_JiaoKanMuBiao_obj : URIRef
    """ 校勘目标对象 """
    op_JiaoKanZiLiao : URIRef
    """ 校勘资料 """
    op_PD_WenXianLaiYuan : URIRef
    """ 所属文献对象 """
    dp_HouZi : URIRef
    """ 后字 """
    dp_JiaoKanJi_text : URIRef
    """ 校勘记文本 """
    dp_PD_Juan : URIRef
    """ 所属卷 """
    dp_PD_WenXianLaiYuan : URIRef
    """ 所属文献 """
    dp_PD_YeMa : URIRef
    """ 所属页码 """
    dp_PD_Zhang : URIRef
    """ 所属章 """
    dp_QianZi : URIRef
    """ 前字 """
    dp_TuoZi : URIRef
    """ 脱字 """
    dp_WuZi : URIRef
    """ 误字 """
    dp_XiuDingHou_text : URIRef
    """ 修订后文本 """
    dp_XiuDingMoShi_text : URIRef
    """ 修订模式文本 """
    dp_YanZi : URIRef
    """ 衍字 """
    dp_Yuan_text : URIRef
    """ 原文本 """
    dp_ZhengZi : URIRef
    """ 正字 """
    c_BenXiao : URIRef
    """ 本校 """
    c_CWLX_Dao : URIRef
    """ 倒 """
    c_CWLX_E : URIRef
    """ 讹 """
    c_CWLX_EDao : URIRef
    """ 既讹且倒 """
    c_CWLX_ETuo : URIRef
    """ 既讹且脱 """
    c_CWLX_ETuoDao : URIRef
    """ 既讹且脱又倒 """
    c_CWLX_ETuoYan : URIRef
    """ 既讹且脱又衍 """
    c_CWLX_EYan : URIRef
    """ 既讹且衍 """
    c_CWLX_EYanDao : URIRef
    """ 既讹且衍又倒 """
    c_CWLX_Tuo : URIRef
    """ 脱 """
    c_CWLX_TuoDao : URIRef
    """ 既脱且倒 """
    c_CWLX_TuoYan : URIRef
    """ 既脱且衍 """
    c_CWLX_TuoYanDao : URIRef
    """ 既脱且衍又倒 """
    c_CWLX_Yan : URIRef
    """ 衍 """
    c_CWLX_YanDao : URIRef
    """ 既衍且倒 """
    c_CWYY_Dao : URIRef
    """ 致倒原因 """
    c_CWYY_E : URIRef
    """ 致讹原因 """
    c_CWYY_Tuo : URIRef
    """ 致脱原因 """
    c_CWYY_Yan : URIRef
    """ 致衍原因 """
    c_CuoWuLeiXing : URIRef
    """ 错误类型 """
    c_CuoWuYuanYin : URIRef
    """ 错误原因 """
    c_DanXiangCuoWu : URIRef
    """ 单项错误 """
    c_DuiXiao : URIRef
    """ 对校 """
    c_JKJLX_BaWoChengDu : URIRef
    """ 校勘把握程度类 """
    c_JKJLX_ChengGuoHuoDeZhe : URIRef
    """ 校勘成果获得者类 """
    c_JKJLX_ZhuZuoMuDi : URIRef
    """ 校勘著作目的类 """
    c_JKZL_BenShuYiBen : URIRef
    """ 本书异本 """
    c_JKZL_QiTaZiLiao : URIRef
    """ 其他资料 """
    c_JKZL_TaShuYinWen : URIRef
    """ 他书引文 """
    c_JiaoKanChengGuoXingShi : URIRef
    """ 校勘成果形式 """
    c_JiaoKanFangFa : URIRef
    """ 校勘方法 """
    c_JiaoKanJi : URIRef
    """ 校勘记 """
    c_JiaoKanJiLeiXing : URIRef
    """ 校勘记类型 """
    c_JiaoKanShiTi : URIRef
    """ 校勘实体 """
    c_JiaoKanZiLiao : URIRef
    """ 校勘资料 """
    c_LiXiao : URIRef
    """ 理校 """
    c_LiangZhongCuoWu : URIRef
    """ 两重错误 """
    c_SanChongCuoWu : URIRef
    """ 三重错误 """
    c_TaXiao : URIRef
    """ 他校 """
    c_WenXianPianDuan : URIRef
    """ 文献片段 """
    i_BenXiao : URIRef
    """ 本校 """
    i_CWLX_Dao : URIRef
    """ 倒 """
    i_CWLX_E : URIRef
    """ 讹 """
    i_CWLX_EDao : URIRef
    """ 既讹且倒 """
    i_CWLX_ETuo : URIRef
    """ 既讹且脱 """
    i_CWLX_ETuoDao : URIRef
    """ 既讹且脱又倒 """
    i_CWLX_ETuoYan : URIRef
    """ 既讹且脱又衍 """
    i_CWLX_EYan : URIRef
    """ 既讹且衍 """
    i_CWLX_EYanDao : URIRef
    """ 既讹且衍又倒 """
    i_CWLX_Tuo : URIRef
    """ 脱 """
    i_CWLX_TuoDao : URIRef
    """ 既脱且倒 """
    i_CWLX_TuoYan : URIRef
    """ 既脱且衍 """
    i_CWLX_TuoYanDao : URIRef
    """ 既脱且衍又倒 """
    i_CWLX_Yan : URIRef
    """ 衍 """
    i_CWLX_YanDao : URIRef
    """ 既衍且倒 """
    i_CWYY_Dao1 : URIRef
    """ 因上下字相关联而倒 """
    i_CWYY_Dao10 : URIRef
    """ 因据误本而乙 """
    i_CWYY_Dao11 : URIRef
    """ 因误据他书而乙 """
    i_CWYY_Dao12 : URIRef
    """ 因政治原因而颠倒原书 """
    i_CWYY_Dao2 : URIRef
    """ 因上下句关联而倒 """
    i_CWYY_Dao3 : URIRef
    """ 因错简错页而倒 """
    i_CWYY_Dao4 : URIRef
    """ 因不明字音而乙 """
    i_CWYY_Dao5 : URIRef
    """ 因不明假借字而乙 """
    i_CWYY_Dao6 : URIRef
    """ 因不明词义而乙 """
    i_CWYY_Dao7 : URIRef
    """ 因不明文义而乙 """
    i_CWYY_Dao8 : URIRef
    """ 因不明修辞手法而乙 """
    i_CWYY_Dao9 : URIRef
    """ 因习见词语而乙 """
    i_CWYY_E1 : URIRef
    """ 因形近而讹 """
    i_CWYY_E10 : URIRef
    """ 因字习见与否而讹 """
    i_CWYY_E11 : URIRef
    """ 因上下文而讹 """
    i_CWYY_E12 : URIRef
    """ 因注文而讹 """
    i_CWYY_E13 : URIRef
    """ 因误改而讹 """
    i_CWYY_E14 : URIRef
    """ 因避讳改字而讹 """
    i_CWYY_E15 : URIRef
    """ 因政治原因而改 """
    i_CWYY_E16 : URIRef
    """ 为方便读者而改 """
    i_CWYY_E17 : URIRef
    """ 因提高文字水平而改 """
    i_CWYY_E2 : URIRef
    """ 因偏旁而讹 """
    i_CWYY_E3 : URIRef
    """ 因字体变化而讹 """
    i_CWYY_E4 : URIRef
    """ 因重文作二画而讹 """
    i_CWYY_E5 : URIRef
    """ 因阙字作空围而讹 """
    i_CWYY_E6 : URIRef
    """ 因字形缺坏而讹 """
    i_CWYY_E7 : URIRef
    """ 一字讹为两字 """
    i_CWYY_E8 : URIRef
    """ 两字讹为一字 """
    i_CWYY_E9 : URIRef
    """ 因假借字而讹 """
    i_CWYY_Tuo1 : URIRef
    """ 因书籍缺损而脱 """
    i_CWYY_Tuo10 : URIRef
    """ 因据他书而删 """
    i_CWYY_Tuo11 : URIRef
    """ 因据误本而删 """
    i_CWYY_Tuo12 : URIRef
    """ 写工阙钞 """
    i_CWYY_Tuo13 : URIRef
    """ 出版单位刊落 """
    i_CWYY_Tuo14 : URIRef
    """ 因避讳而删 """
    i_CWYY_Tuo15 : URIRef
    """ 因政治原因而删 """
    i_CWYY_Tuo2 : URIRef
    """ 因重文而脱 """
    i_CWYY_Tuo3 : URIRef
    """ 因忽略重文符号而脱 """
    i_CWYY_Tuo4 : URIRef
    """ 因上下文而脱 """
    i_CWYY_Tuo5 : URIRef
    """ 正文误入注文 """
    i_CWYY_Tuo6 : URIRef
    """ 因字体残阙而删 """
    i_CWYY_Tuo7 : URIRef
    """ 因不识假借字而删 """
    i_CWYY_Tuo8 : URIRef
    """ 因不明词义而删 """
    i_CWYY_Tuo9 : URIRef
    """ 因不审文义而删 """
    i_CWYY_Yan1 : URIRef
    """ 因形近而衍 """
    i_CWYY_Yan10 : URIRef
    """ 涉上下文而衍 """
    i_CWYY_Yan11 : URIRef
    """ 误叠 """
    i_CWYY_Yan12 : URIRef
    """ 涉注文而衍 """
    i_CWYY_Yan13 : URIRef
    """ 因据误本文字而加 """
    i_CWYY_Yan14 : URIRef
    """ 因误据他篇而加 """
    i_CWYY_Yan15 : URIRef
    """ 因误据他书而加 """
    i_CWYY_Yan16 : URIRef
    """ 本无阙文而误加空围 """
    i_CWYY_Yan17 : URIRef
    """ 为牟利而加 """
    i_CWYY_Yan18 : URIRef
    """ 为说明自己的观点而加 """
    i_CWYY_Yan19 : URIRef
    """ 为便于阅读而加 """
    i_CWYY_Yan2 : URIRef
    """ 因残字而衍 """
    i_CWYY_Yan20 : URIRef
    """ 后世编史添加 """
    i_CWYY_Yan3 : URIRef
    """ 因不明通假字而衍 """
    i_CWYY_Yan4 : URIRef
    """ 因两字义同而衍 """
    i_CWYY_Yan5 : URIRef
    """ 因不明词义而衍 """
    i_CWYY_Yan6 : URIRef
    """ 因不明文义而衍 """
    i_CWYY_Yan7 : URIRef
    """ 因不明句读而衍 """
    i_CWYY_Yan8 : URIRef
    """ 注文误入正文 """
    i_CWYY_Yan9 : URIRef
    """ 校者旁记之字误入正文 """
    i_DuiXiao : URIRef
    """ 对校 """
    i_JKJLX_BaWoChengDu1 : URIRef
    """ 是非校勘记 """
    i_JKJLX_BaWoChengDu2 : URIRef
    """ 倾向校勘记 """
    i_JKJLX_BaWoChengDu3 : URIRef
    """ 存疑校勘记 """
    i_JKJLX_BaWoChengDu4 : URIRef
    """ 异同校勘记 """
    i_JKJLX_ChengGuoHuoDeZhe1 : URIRef
    """ 引用前人成果的校勘记 """
    i_JKJLX_ChengGuoHuoDeZhe2 : URIRef
    """ 今人成果的校勘记 """
    i_JKJLX_ChengGuoHuoDeZhe3 : URIRef
    """ 合用前人和今人成果的校勘记 """
    i_JKJLX_ZhuZuoMuDi1 : URIRef
    """ 一般校勘记 """
    i_JKJLX_ZhuZuoMuDi2 : URIRef
    """ 集校校勘记 """
    i_JKZL_BenShuYiBen1 : URIRef
    """ 稿本 """
    i_JKZL_BenShuYiBen2 : URIRef
    """ 钞本 """
    i_JKZL_BenShuYiBen3 : URIRef
    """ 拓本 """
    i_JKZL_BenShuYiBen4 : URIRef
    """ 印本 """
    i_JKZL_BenShuYiBen5 : URIRef
    """ 注本 """
    i_JKZL_BenShuYiBen6 : URIRef
    """ 选本 """
    i_JKZL_BenShuYiBen7 : URIRef
    """ 校本 """
    i_JKZL_QiTaZiLiao1 : URIRef
    """ 甲骨文 """
    i_JKZL_QiTaZiLiao2 : URIRef
    """ 金文 """
    i_JKZL_QiTaZiLiao3 : URIRef
    """ 石刻 """
    i_JKZL_QiTaZiLiao4 : URIRef
    """ 古印、封泥 """
    i_JKZL_QiTaZiLiao5 : URIRef
    """ 其他书籍中的有关资料 """
    i_JKZL_QiTaZiLiao6 : URIRef
    """ 专家学者的意见 """
    i_JKZL_TaShuYinWen1 : URIRef
    """ 古类书引文 """
    i_JKZL_TaShuYinWen2 : URIRef
    """ 古书注引文 """
    i_JKZL_TaShuYinWen3 : URIRef
    """ 其他古书引文 """
    i_JiaoKanChengGuoXingShi1 : URIRef
    """ 定本 """
    i_JiaoKanChengGuoXingShi2 : URIRef
    """ 定本附校勘记 """
    i_JiaoKanChengGuoXingShi3 : URIRef
    """ 底本附校勘记 """
    i_JiaoKanChengGuoXingShi4 : URIRef
    """ 单行的校勘记 """
    i_JiaoKanChengGuoXingShi5 : URIRef
    """ 与注释混合的校勘记 """
    i_JiaoKanChengGuoXingShi6 : URIRef
    """ 载于笔记中的校勘记 """
    i_JiaoKanChengGuoXingShi7 : URIRef
    """ 用单篇文章发表的校勘记 """
    i_LiXiao : URIRef
    """ 理校 """
    i_TaXiao : URIRef
    """ 他校 """